/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as EmpleadosRouteImport } from './routes/empleados'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as SedesRouteImport } from './routes/sedes'
import { Route as TiposRouteImport } from './routes/tipos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadosRoute = EmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const SedesRoute = SedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => rootRouteImport,
} as any)
const TiposRoute = TiposRouteImport.update({
  id: '/tipos',
  path: '/tipos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/empleados': typeof EmpleadosRoute
  '/movimientos': typeof MovimientosRoute
  '/sedes': typeof SedesRoute
  '/tipos': typeof TiposRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/empleados': typeof EmpleadosRoute
  '/movimientos': typeof MovimientosRoute
  '/sedes': typeof SedesRoute
  '/tipos': typeof TiposRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/empleados': typeof EmpleadosRoute
  '/movimientos': typeof MovimientosRoute
  '/sedes': typeof SedesRoute
  '/tipos': typeof TiposRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/areas' | '/empleados' | '/movimientos' | '/sedes' | '/tipos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas' | '/empleados' | '/movimientos' | '/sedes' | '/tipos'
  id:
    | '__root__'
    | '/'
    | '/areas'
    | '/empleados'
    | '/movimientos'
    | '/sedes'
    | '/tipos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasRoute: typeof AreasRoute
  EmpleadosRoute: typeof EmpleadosRoute
  MovimientosRoute: typeof MovimientosRoute
  SedesRoute: typeof SedesRoute
  TiposRoute: typeof TiposRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleados': {
      id: '/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof EmpleadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sedes': {
      id: '/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof SedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipos': {
      id: '/tipos'
      path: '/tipos'
      fullPath: '/tipos'
      preLoaderRoute: typeof TiposRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasRoute: AreasRoute,
  EmpleadosRoute: EmpleadosRoute,
  MovimientosRoute: MovimientosRoute,
  SedesRoute: SedesRoute,
  TiposRoute: TiposRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
